# Generated by Django 3.1.6 on 2021-05-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogapp', '0007_auto_20210506_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user_permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='auth.permission'),
        ),
    ]
